### ISSUE TITLE
Doesn't seem to work on webkit (Chrome/Safari on OS X)

### ISSUE THREAD

**Issue by pax** [fasterthanlime/jsmad#13]
**No sound in webkit** (tested in Chrome 13 & Safari 5) on **OS X** 10.5.8. Works on FF 5.0

**Comment by nddrylliog** [comment]
Yup, can't get it to work on my Chrome Canary (14.0.796.0) on Windows as well.

Have you restarted your browser after enabling 'Web Audio API' in 'about:flags' ?

**Comment by pax** [comment]
In both the it loads the box with the artwork and play button.
- In Chrome the bar advances as if the song is played but no sound.
- In Safari there's no bar - only its border, but nothing happens (song doesn't seem to be loading).

**Comment by nddrylliog** [comment]
That the box loads means the Official.fm Simple API requests works - yay ajax!

That the bar advances means that the streaming is working from our mp3.jsmad.org CDN - yay ajax!

That there's no sound is probably that you don't have Web Audio API enabled (see my previous comment) or.. another mysterious issue with Chrome - there was this bug that we had to wait 2 seconds before trying to play sound.. see http://code.google.com/p/chromium/issues/detail?id=82795

**Comment by pax** [comment]
now **it works** on Chrome - **after enabling the Web Audio API**. Which I didn't know I had to.

**Comment by nddrylliog** [comment]
Yeah, sorry for that - communication has been a bit shaky on the various
news site. It's now mentioned in the readme. Good to hear!

On Sat, Jun 18, 2011 at 11:57 PM, pax <
reply@reply.github.com>wrote:

> now **it works** on Chrome - **after enabling the Web Audio API**. Which I
> didn't know I had to.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nddrylliog/jsmad/issues/13#issuecomment-1394738

## 

Amos Wenger
Community Development Engineer
official.fm - "The Do It Yourself Music Club"
I'm @nddrylliog https://github.com/nddrylliog on GitHub

**Comment by pax** [comment]
As for Safari I haven't installed [this build](http://chromium.googlecode.com/svn/trunk/samples/audio/bin/WebKit-audio.05Jan2011.zip|) so I'm closing the issue, it was just my misinformation.
