### ISSUE TITLE
this.state.buffer is undefined

### ISSUE THREAD

**Issue by jannewmarch** [fasterthanlime/jsmad#17]
Tried to get a minimal HTML page + Javascript to see jsmad working, but keep getting Javascript error "this.state.buffer is undefined" in all.js line 17033. 

My HTML is

<pre>
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
&lt;meta charset="utf-8" /&gt;
&lt;!-- &lt;base href="http://jsmad.org" /&gt; --&gt;
&lt;title&gt;jsmad - javascript mp3 decoder&lt;/title&gt;
&lt;link rel="stylesheet" href="css/style.css" type="text/css" media="screen" /&gt;

&lt;script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="all.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="audiolib.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="officialfm.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="play.js"&gt;&lt;/script&gt;

&lt;/head&gt;

&lt;body onload="domReady()"&gt;

&lt;/body&gt;
&lt;/html&gt;
</pre>

and my JavaScript is

<pre>
var globalPlayer = null;

function domReady() {
    var url = "http://mp3.jsmad.org/mp3s/176/176848.mp3";
    Mad.Player.fromURL(url, usePlayer);
}

function usePlayer (player) {
    if (globalPlayer) globalPlayer.destroy();
    globalPlayer = player;
    player.setPlaying(true);
    player.createDevice();
}
</pre>

I'm obviously doing something wrong...

**Comment by auroranockert** [comment]
Not really, it just means that the browser could not access the stream. It is a cross-domain issue, you cannot do ajax against mp3.jsmad.org from domains other than mp3.jsmad.org or jsmad.org.

**Comment by auroranockert** [comment]
(Ps. Sorry for the useless error handling.)

**Comment by nddrylliog** [comment]
Hmm.. what is play.js?

And yes, I remember weird issues with this.buffer being undefined, mostly
when the browser didn't support the XHRs we were using such as Chrome 12 on
Windows. What browser are you testing it with?

On Tue, Jun 21, 2011 at 1:50 PM, jannewmarch <
reply@reply.github.com>wrote:

> Tried to get a minimal HTML page + Javascript to see jsmad working, but
> keep getting Javascript error "this.state.buffer is undefined" in all.js
> line 17033.
> 
> My HTML is
> 
> <pre>
> &lt;!DOCTYPE html&gt;
> &lt;html&gt;
> &lt;head&gt;
> &lt;meta charset="utf-8" /&gt;
> &lt;!-- &lt;base href="http://jsmad.org" /&gt; --&gt;
> &lt;title&gt;jsmad - javascript mp3 decoder&lt;/title&gt;
> &lt;link rel="stylesheet" href="css/style.css" type="text/css"
> media="screen" /&gt;
> 
> &lt;script type="text/javascript" src="
> http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.js
> "&gt;&lt;/script&gt;
> &lt;script type="text/javascript" src="all.js"&gt;&lt;/script&gt;
> &lt;script type="text/javascript" src="audiolib.min.js"&gt;&lt;/script&gt;
> &lt;script type="text/javascript" src="officialfm.js"&gt;&lt;/script&gt;
> &lt;script type="text/javascript" src="play.js"&gt;&lt;/script&gt;
> 
> 
> &lt;/head&gt;
> 
> &lt;body onload="domReady()"&gt;
> 
> &lt;/body&gt;
> &lt;/html&gt;
> </pre>
> 
> 
> and my JavaScript is
> 
> <pre>
> var globalPlayer = null;
> 
> function domReady() {
>    var url = "http://mp3.jsmad.org/mp3s/176/176848.mp3";
>    Mad.Player.fromURL(url, usePlayer);
> }
> 
> function usePlayer (player) {
>    if (globalPlayer) globalPlayer.destroy();
>    globalPlayer = player;
>    player.setPlaying(true);
>    player.createDevice();
> }
> </pre>
> 
> 
> I'm obviously doing something wrong...
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nddrylliog/jsmad/issues/17

## 

Amos Wenger
Community Development Engineer
official.fm - "The Do It Yourself Music Club"
I'm @nddrylliog https://github.com/nddrylliog on GitHub

**Comment by base698** [comment]
I get this same error locally and hitting a soundcloud url, but the file eventually plays, just throws a bunch (100s I'd say) of these errors before it starts.

**Comment by nddrylliog** [comment]
@JensNockert or somebody at audiocogs, please re-post that issue to https://github.com/audiocogs/jsmad where it belongs. Thanks.
