### ISSUE TITLE
no local files upload form in Firefox 7.0.1

### ISSUE THREAD

**Issue by automata** [fasterthanlime/jsmad#28]
I'm using Firefox 7.0.1 and the upload form for local mp3 files is not working in http://jsmad.org. Any suggestion?

**Comment by auroranockert** [comment]
On Mar 12, 2012, at 9:14 PM, Vilson Vieira wrote:

> I'm using Firefox 7.0.1 and the upload form for local mp3 files is not working. Any suggestion?

Does it work using Firefox 10 or later?

Is it just a single file that isn't working, or do no files work?

I just tested on 12.0a2 and all my test files work, but I am not sure how old browsers we support.

**Comment by automata** [comment]
Testing now with FF 10 and it is working. Silly me using ancient FF. Just the loading bar is not working properly, but maybe it could be because of my slow connection.

**Comment by automata** [comment]
And with FF 12.a2 it is working like a charm! I think we can close this issue.

**Comment by auroranockert** [comment]
Awesome, I think the loading bar is broken, yes. (I cannot remember if we ever had a loading bar? /cc @nddrylliog)

**Comment by automata** [comment]
Yeah, I confused the playing bar with the loading.

**Comment by nddrylliog** [comment]
@JensNockert Yes, when streaming from HTTP we have a 'loading bar' and yes it was never really reliable, this is old jsmad code :) The codecs code is much cleaner imho.
