### ISSUE TITLE
request for feature: decode from URL

### ISSUE THREAD

**Issue by automata** [fasterthanlime/jsmad#29]
The official.fm id and local files options on http://jsmad.org are interesting but It'd be also interesting to decode a file from an URL.

**Comment by auroranockert** [comment]
On Mar 12, 2012, at 9:20 PM, Vilson Vieira wrote:

> The official.fm id and local files options on http://jsmad.org are interesting but It'd be also interesting to decode a file from an URL.

That is a limitation of the browser APIs, we cannot access arbitrary URLs (for security reasons.)

CORS to some degree reduces that limitation.

**Comment by automata** [comment]
We totally forgotten about CORS, you are right!

**Comment by auroranockert** [comment]
I closed this, would love to implement it once browsers allow it.

(I think we use CORS on http://codecs.ofmlabs.org to supply the songs, if you want an example of using jsmad like that)

**Comment by automata** [comment]
Thank you Jens, pretty good work on codes!
