### ISSUE TITLE
Nothing happens in Chrome. Many errors.

### ISSUE THREAD

**Issue by trusktr** [fasterthanlime/jsmad#30]
I have Chrome 19.0.1084.52 m and neither the jsmad or alac players work on http://codecs.ofmlabs.org/.. Chrome shows many errors in the console.

**Comment by auroranockert** [comment]
It works for me in Chrome 19, could you send a log of the errors and which OS you're running it on?

**Comment by trusktr** [comment]
Sure, this is what the output looks like when trying to use the jsmad player on the left: http://pastie.org/3979933.

Is the "GET http://codecs.ofmlabs.org/media/planets@96000.mp3 404 (Not Found) jsmad.js:16189" error causing all the "Uncaught Header decoding failed jsmad.js:14430" errors?

I'm in Windows 7 right now by the way.

**Comment by trusktr** [comment]
And the output looks like this when I try to use the alac player on the right:
Using ArrayBuffer --- jsmad.js:15
HEAD http://codecs.ofmlabs.org/media/love@96000.caf 404 (Not Found) --- alac.js:624

**Comment by auroranockert** [comment]
I understand the problem, JSMad has issues with sample rate. We only support 44.1kHz and 48kHz output in Chrome on codecs, your hardware is set to 96kHz for some reason. It is really a missing feature of the Chrome Web Audio API.
