### ISSUE TITLE
Where's the documentation? How do I use jsmad?

### ISSUE THREAD

**Issue by trusktr** [fasterthanlime/jsmad#31]
We need an easy way to use jsmad without having to dig through source code to figure it out.

**Comment by trusktr** [comment]
An API.

**Comment by nddrylliog** [comment]
Hey @trusktr, jsmad has been discontinued, but its code has been refactored and integrated into aurora.js, a framework for JS audio decoders, you might want to check it out instead: https://github.com/ofmlabs/aurora.js

**Comment by trusktr** [comment]
Noted. Thanks for this amazing contribution.
