### ISSUE TITLE
What happened to the site?  

### ISSUE THREAD

**Issue by base698** [fasterthanlime/jsmad#32]
jsmad fowards to ooc-lang now.  Also can't get a working copy of audiolib to try it locally.

**Comment by nddrylliog** [comment]
Hey, sorry about that, forgot to renable the vhost for jsmad.org on my VPS. All fixed now.

All the jsmad/audiolib projects have been moved to audiocogs btw, I'll let you read here for info on what happened: http://audiocogs.org/articles/2013/03/18/moving-on/

Closing.
