### ISSUE TITLE
JSMad.org is down ?

### ISSUE THREAD

**Issue by daslicht** [fasterthanlime/jsmad#33]
JSMad.org is down ?

**Comment by auroranockert** [comment]
Yes, but a codec example is available on http://audiocogs.org/codecs/mp3/

**Comment by daslicht** [comment]
Thank you !!!! :dancer:

**Comment by daslicht** [comment]
Cool,
so I could use this to stream audio from Node to a http client ?

**Comment by auroranockert** [comment]
Yes, but not all browsers support it (IE and most mobile browsers doesn't) and some devices are just plain too slow.

**Comment by daslicht** [comment]
awesome

**Comment by daslicht** [comment]
As far as I got more time I try to stream audio from node via a socket to jsmad and try to create a kind of radio. Or is therer already something like this somewhere ?

**Comment by auroranockert** [comment]
I don't think anyone has tried that. But it would be awesome!

**Comment by daslicht** [comment]
:D Yeah!
